---
title: "R Coding Exercise"

By: Vinayak Revisanker zuk198
---

# load dslabs package
library("dslabs")
#look at help file for gapminder data
help(gapminder)


#g et an overview of data structure
str(gapminder)

# get a summary of data
summary(gapminder)


class(gapminder)

# Assign data from Africa to africadata
africadata <- subset(gapminder, continent == "Africa")

# overview of africadata
str(africadata)

# summary of africadata
summary(africadata)

# 2 new datasets
africadata_inf_life <- africadata[, c("infant_mortality", "life_expectancy")]
africadata_pop_life <- africadata[, c("population", "life_expectancy")]

# for africadata_inf_life
str(africadata_inf_life)
summary(africadata_inf_life)

# for africadata_inf_life
str(africadata_pop_life)
summary(africadata_pop_life)


# plotting data

#plotting for infant mortality and life expectancy
plot(africadata_inf_life$infant_mortality, africadata_inf_life$life_expectancy,
     xlab = "Infant Mortality", ylab = "Life Expectancy", main = "Life Expectancy vs. Infant Mortality")
     

plot(africadata_pop_life$population, africadata_pop_life$life_expectancy,
     xlab = "Population (log scale)", ylab = "Life Expectancy", main = "Life Expectancy vs. Population Size",
     log = "x")
     
     
# More data processing

missing_years <- table(africadata$year[is.na(africadata$infant_mortality)])
missing_years # Display the years with missing infant mortality data

# Extract data for the year 2000
africadata_2000 <- subset(africadata, year == 2000) # Subset data for the year 2000

#Overview and summary of the 2000 dataset
str(africadata_2000) # Display the structure of africadata_2000
summary(africadata_2000) # Display a summary of africadata_2000




# More plotting

# #plotting  for infant mortality and life expectancy in the year 2000
plot(africadata_2000$infant_mortality, africadata_2000$life_expectancy,
     xlab = "Infant Mortality", ylab = "Life Expectancy", main = "Life Expectancy vs. Infant Mortality (2000)")

# Plot life expectancy and population size in the year 2000
plot(africadata_2000$population, africadata_2000$life_expectancy,
     xlab = "Population (log scale)", ylab = "Life Expectancy", main = "Life Expectancy vs. Population Size (2000)",
     log = "x")

# Simple model fits

# simple model fits for life expectancy and infant mortality based on the data from Africa from year 2000
model_fit1 <- lm(life_expectancy ~ infant_mortality, data = africadata_2000) 
summary(model_fit1) 

#simple model fits for life expectancy and population based on the data from Africa from year 2000
model_fit2 <- lm(life_expectancy ~ population, data = africadata_2000) 
summary(model_fit2)
summary(model_fit2) 
